source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'rails-api'
gem 'pg'

gem 'active_model_serializers'
gem 'flowdock'
gem 'gravatar-ultimate'
gem 'kaminari'
gem 'octokit'
gem 'pundit'
gem 'rack-rewrite'
gem 'skylight'
gem 'unicorn'

group :production do
  gem 'rails_12factor'
end

group :development do
  gem 'spring'
  gem 'rack-cors', require: 'rack/cors'
end

group :test do
  gem 'shoulda-matchers', require: false
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.0.0'
end
