source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'rails-api'
gem 'pg'

gem 'active_model_serializers'
gem 'octokit'
gem 'rack-cors', require: 'rack/cors'

group :development do
  gem 'spring'
end

group :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'shoulda-matchers', require: false
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'pry-rails'
end
